-- CreateTable
CREATE TABLE `PANApplication` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `lastName` VARCHAR(191) NOT NULL,
    `firstName` VARCHAR(191) NOT NULL,
    `middleName` VARCHAR(191) NOT NULL,
    `nameOnCard` VARCHAR(191) NOT NULL,
    `dateOfBirth` DATETIME(3) NOT NULL,
    `gender` VARCHAR(191) NOT NULL,
    `fatherLastName` VARCHAR(191) NOT NULL,
    `fatherFirstName` VARCHAR(191) NOT NULL,
    `fatherMiddleName` VARCHAR(191) NOT NULL,
    `aadhaarNumber` VARCHAR(191) NOT NULL,
    `nameAsPerAadhaar` VARCHAR(191) NOT NULL,
    `mobileNumber` VARCHAR(191) NOT NULL,
    `emailAddress` VARCHAR(191) NOT NULL,
    `flatRoomDoorBlockNo` VARCHAR(191) NOT NULL,
    `buildingVillageName` VARCHAR(191) NOT NULL,
    `roadStreetLanePostOffice` VARCHAR(191) NOT NULL,
    `areaLocalitySubDivision` VARCHAR(191) NOT NULL,
    `stateUnionTerritory` VARCHAR(191) NOT NULL,
    `townCityDistrict` VARCHAR(191) NOT NULL,
    `pinCode` VARCHAR(191) NOT NULL,
    `panCardType` VARCHAR(191) NOT NULL,
    `proofOfIdentity` VARCHAR(191) NOT NULL,
    `proofOfAddress` VARCHAR(191) NOT NULL,
    `proofOfDOB` VARCHAR(191) NOT NULL,
    `aadharCardImage` VARCHAR(191) NOT NULL,
    `aadharBack` VARCHAR(191) NOT NULL,
    `photo` VARCHAR(191) NOT NULL,
    `signature` VARCHAR(191) NOT NULL,
    `charges` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
